openapi: 3.0.0
info:
  title: T-shirt store
  description: Create a api in nodeJs
  version: 1.1.0
  contact:
    email: boarsedarshan77@gmail.com
    url: "https://production-first.herokuapp.com/"

# servers:
#   - url: http://localhost:4000/api/v1
#     description: For the localhost - regular
#   - url: https://localhost:4000/api/v1
#     description: For the localhost - secure

servers:
  - url: "{protocols}://localhost:4000/api/{version}"
    description: For the localhost
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocols:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      summary: returns a greet message from t-shirt store
      tags:
        - String
      responses:
        200:
          description: All good and success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  greeting:
                    type: string
        400:
          description: Bad request
        500:
          description: Internal server error

  /signup:
    post:
      summary: signup a new user. required files are - name, email, password and photo
      tags:
        - User
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - email
                - password
                - photo
              properties:
                name:
                  type: string
                  required: true
                email:
                  type: string
                password:
                  type: string
                photo:
                  in: formData
                  description: The uploaded file data
                  type: file
                  format: binary
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  token:
                    type: string
                  user:
                    type: object
                    properties:
                      name:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
                      photo:
                        type: object
                        properties:
                          id:
                            type: string
                          secure_url:
                            type: string
                      _id:
                        type: string
                      createdAt:
                        type: string
        400:
          description: Bad request
        500:
          description: internal server error
